#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII
feh --bg-fill --randomize ~/Wallpapers/* &
#com.wire.WireDesktop &

bspc config border_width        0
bspc config window_gap          10
bspc config right_padding       5
bspc config left_padding        5
bspc config bottom_padding      0

bspc config normal_border_color '#FFFFFF'
bspc config focused_border_color '#FFFFFF'
bspc config active_border_color '#FFFFFF'

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config presel_feedback_color '#1ab2ff'

picom -f & 
~/.config/polybar/launch.sh
